@startuml
abstract class at.archistar.crypto.random.BaseRandomAlgorithm
abstract class at.archistar.crypto.secretsharing.GeometricSecretSharing
class at.archistar.crypto.CryptoEngineFactory
class at.archistar.crypto.CSSEngine
class at.archistar.crypto.PSSEngine
class at.archistar.crypto.data.InvalidParametersException
class at.archistar.crypto.data.CSSShare
class at.archistar.crypto.data.RabinShare
class at.archistar.crypto.data.ShamirShare
class at.archistar.crypto.data.KrawczykShare
class at.archistar.crypto.data.BrokenShare
class at.archistar.crypto.data.PSSShare
class at.archistar.crypto.data.ShareFactory
class at.archistar.crypto.data.ReconstructionResult
class at.archistar.crypto.decode.BerlekampWelchDecoder
class at.archistar.crypto.decode.BerlekampWelchDecoderFactory
class at.archistar.crypto.decode.ErasureDecoder
class at.archistar.crypto.decode.ErasureDecoderFactory
class at.archistar.crypto.decode.UnsolvableException
class at.archistar.crypto.informationchecking.CevallosUSRSS
class at.archistar.crypto.informationchecking.RabinBenOrRSS
class at.archistar.crypto.mac.BCMacHelper
class at.archistar.crypto.mac.BCPoly1305MacHelper
class at.archistar.crypto.mac.BCShortenedMacHelper
class at.archistar.crypto.mac.BCShortenedMacHelperFactory
class at.archistar.crypto.mac.JavaMacHelper
class at.archistar.crypto.mac.PolyHash
class at.archistar.crypto.math.gf256.GF256
class at.archistar.crypto.math.gf256.GF256Matrix
class at.archistar.crypto.math.gf256.GF256PolyHelper
class at.archistar.crypto.random.BCDigestRandomSource
class at.archistar.crypto.random.CTRPRNG
class at.archistar.crypto.random.FakeRandomSource
class at.archistar.crypto.random.JavaSecureRandom
class at.archistar.crypto.random.StreamPRNG
class at.archistar.crypto.secretsharing.KrawczykCSS
class at.archistar.crypto.secretsharing.RabinIDS
class at.archistar.crypto.secretsharing.ReconstructionException
class at.archistar.crypto.secretsharing.ShamirPSS
class at.archistar.crypto.secretsharing.WeakSecurityException
class at.archistar.crypto.symmetric.AESEncryptor
class at.archistar.crypto.symmetric.AESGCMEncryptor
class at.archistar.crypto.symmetric.ChaCha20Encryptor
interface at.archistar.crypto.data.Share
interface at.archistar.crypto.data.InformationCheckingShare
interface at.archistar.crypto.CryptoEngine
interface at.archistar.crypto.decode.Decoder
interface at.archistar.crypto.decode.DecoderFactory
interface at.archistar.crypto.informationchecking.InformationChecking
interface at.archistar.crypto.mac.MacHelper
interface at.archistar.crypto.random.RandomSource
interface at.archistar.crypto.secretsharing.SecretSharing
interface at.archistar.crypto.symmetric.Encryptor
at.archistar.crypto.random.BaseRandomAlgorithm --|> at.archistar.crypto.random.RandomSource
at.archistar.crypto.secretsharing.BaseSecretSharing --|> at.archistar.crypto.secretsharing.SecretSharing
at.archistar.crypto.secretsharing.GeometricSecretSharing --|> at.archistar.crypto.secretsharing.BaseSecretSharing
at.archistar.crypto.CSSEngine --|> at.archistar.crypto.CryptoEngine
at.archistar.crypto.PSSEngine --|> at.archistar.crypto.CryptoEngine
at.archistar.crypto.data.CSSShare --|> at.archistar.crypto.data.KrawczykShare
at.archistar.crypto.data.RabinShare --|> at.archistar.crypto.data.Share
at.archistar.crypto.data.ShamirShare --|> at.archistar.crypto.data.Share
at.archistar.crypto.data.KrawczykShare --|> at.archistar.crypto.data.Share
at.archistar.crypto.data.PSSShare --|> at.archistar.crypto.data.ShamirShare
at.archistar.crypto.data.PSSShare --|> at.archistar.crypto.data.InformationCheckingShare
at.archistar.crypto.data.InformationCheckingShare --|> at.archistar.crypto.data.Share
at.archistar.crypto.data.BrokenShare --|> at.archistar.crypto.data.Share
at.archistar.crypto.decode.BerlekampWelchDecoder --|> at.archistar.crypto.decode.Decoder
at.archistar.crypto.decode.BerlekampWelchDecoderFactory --|> at.archistar.crypto.decode.DecoderFactory
at.archistar.crypto.decode.ErasureDecoder --|> at.archistar.crypto.decode.Decoder
at.archistar.crypto.decode.ErasureDecoderFactory --|> at.archistar.crypto.decode.DecoderFactory
at.archistar.crypto.informationchecking.CevallosUSRSS --|> at.archistar.crypto.informationchecking.RabinBenOrRSS
at.archistar.crypto.informationchecking.RabinBenOrRSS --|> at.archistar.crypto.informationchecking.InformationChecking
at.archistar.crypto.mac.BCMacHelper --|> at.archistar.crypto.mac.MacHelper
at.archistar.crypto.mac.BCPoly1305MacHelper --|> at.archistar.crypto.mac.MacHelper
at.archistar.crypto.mac.BCShortenedMacHelper --|> at.archistar.crypto.mac.MacHelper
at.archistar.crypto.mac.JavaMacHelper --|> at.archistar.crypto.mac.MacHelper
at.archistar.crypto.mac.PolyHash --|> at.archistar.crypto.mac.MacHelper
at.archistar.crypto.random.BCDigestRandomSource --|> at.archistar.crypto.random.RandomSource
at.archistar.crypto.random.CTRPRNG --|> at.archistar.crypto.random.BaseRandomAlgorithm
at.archistar.crypto.random.FakeRandomSource --|> at.archistar.crypto.random.RandomSource
at.archistar.crypto.random.JavaSecureRandom --|> at.archistar.crypto.random.RandomSource
at.archistar.crypto.random.StreamPRNG --|> at.archistar.crypto.random.BaseRandomAlgorithm
at.archistar.crypto.secretsharing.KrawczykCSS --|> at.archistar.crypto.secretsharing.BaseSecretSharing
at.archistar.crypto.secretsharing.RabinIDS --|> at.archistar.crypto.secretsharing.GeometricSecretSharing
at.archistar.crypto.secretsharing.ShamirPSS --|> at.archistar.crypto.secretsharing.GeometricSecretSharing
at.archistar.crypto.symmetric.AESEncryptor --|> at.archistar.crypto.symmetric.Encryptor
at.archistar.crypto.symmetric.AESGCMEncryptor --|> at.archistar.crypto.symmetric.Encryptor
at.archistar.crypto.symmetric.ChaCha20Encryptor --|> at.archistar.crypto.symmetric.Encryptor
@enduml
